apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccount: myuser
  containers:
    - image: nginx
      name: nginx
      envFrom:
        - configMapRef:
            name: config5
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
