apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - sleep 3600
      image: busybox
      name: busybox1
      resources: {}
      volumeMounts:
        - mountPath: /etc/foo
          name: emptydir
    - args:
        - /bin/sh
        - -c
        - sleep 3600
      image: busybox
      name: busybox2
      resources: {}
      volumeMounts:
        - mountPath: /etc/foo
          name: emptydir
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: emptydir
      emptyDir: {}
status: {}
