apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - args:
        - notexist
      image: busybox
      name: busybox
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
