apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: work-dir
  initContainers:
    - args:
        - "/bin/sh"
        - -c
        - "wget -O /work-dir/index.html http://neverssl.com/online"
      image: busybox
      name: busybox
      volumeMounts:
        - mountPath: /work-dir
          name: work-dir

  volumes:
    - name: work-dir
      emptyDir: {}
