apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: work-dir
  initContainers:
    - args:
        - "/bin/sh"
        - -c
        - "wget -O /work-dir/index.html http://neverssl.com/online"
      image: busybox
      name: busybox
      volumeMounts:
        - mountPath: /work-dir
          name: work-dir

  volumes:
    - name: work-dir
      emptyDir: {}
# 終了後下記コマンドを実行し、IPアドレスを調査.その後獲得したIPアドレスでwgetする
# kubectl get pod -o wide
# kubectl run busybox --image=busybox --restart=Never -- /bin/sh -c "wget -O- 172.17.0.7"
