apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
spec:
  completions: 5
  parallelism: 5
  template:
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - echo hello;sleep 30;echo world
          image: busybox
          name: busybox
          resources: {}
      restartPolicy: Never
status: {}
